"""Se añadio nullable a la tabla ventas en id empleado y cliente 

Revision ID: 1f3f235a13cd
Revises: a2f450519a68
Create Date: 2025-11-18 22:57:44.548209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3f235a13cd'
down_revision: Union[str, Sequence[str], None] = 'a2f450519a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'id_cliente',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('ventas', 'id_empleado',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'id_empleado',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('ventas', 'id_cliente',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
