"""reingreso de todas las tablas

Revision ID: 1f578c049465
Revises: 
Create Date: 2025-10-13 19:57:26.603922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f578c049465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_index(op.f('ix_cargos_tipo'), 'cargos', ['tipo'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_tipo'), 'categorias', ['tipo'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_apellido'), 'proveedores', ['apellido'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=False)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_table('empleados',
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('id_cargo', sa.BigInteger(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id_cargo'], ),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleados_activo'), 'empleados', ['activo'], unique=False)
    op.create_index(op.f('ix_empleados_apellido'), 'empleados', ['apellido'], unique=False)
    op.create_index(op.f('ix_empleados_email'), 'empleados', ['email'], unique=False)
    op.create_index(op.f('ix_empleados_nombre'), 'empleados', ['nombre'], unique=False)
    op.create_index(op.f('ix_empleados_password_hash'), 'empleados', ['password_hash'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.BigInteger(), nullable=True),
    sa.Column('costo_venta', sa.INTEGER(), nullable=True),
    sa.Column('Cantidad', sa.INTEGER(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_Cantidad'), 'productos', ['Cantidad'], unique=False)
    op.create_index(op.f('ix_productos_costo_venta'), 'productos', ['costo_venta'], unique=False)
    op.create_index(op.f('ix_productos_descripcion'), 'productos', ['descripcion'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('telefonos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('id__proveedor', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id__proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefonos_id'), 'telefonos', ['id'], unique=False)
    op.create_index(op.f('ix_telefonos_num'), 'telefonos', ['num'], unique=False)
    op.create_table('detalles_proveedor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=True),
    sa.Column('proveedor_id', sa.BigInteger(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('empleado_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_proveedor_cantidad'), 'detalles_proveedor', ['cantidad'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_detalle'), 'detalles_proveedor', ['detalle'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_id'), 'detalles_proveedor', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_precio_unit'), 'detalles_proveedor', ['precio_unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_proveedor_precio_unit'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_id'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_detalle'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_cantidad'), table_name='detalles_proveedor')
    op.drop_table('detalles_proveedor')
    op.drop_index(op.f('ix_telefonos_num'), table_name='telefonos')
    op.drop_index(op.f('ix_telefonos_id'), table_name='telefonos')
    op.drop_table('telefonos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_descripcion'), table_name='productos')
    op.drop_index(op.f('ix_productos_costo_venta'), table_name='productos')
    op.drop_index(op.f('ix_productos_Cantidad'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_empleados_password_hash'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_nombre'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_email'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_apellido'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_activo'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_apellido'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_categorias_tipo'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_cargos_tipo'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
