"""se añadio columna precio anterior en la tabla historial de precios

Revision ID: 3478bfda4cf8
Revises: ccc0c3c5b738
Create Date: 2025-10-22 13:34:28.456816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3478bfda4cf8'
down_revision: Union[str, Sequence[str], None] = 'ccc0c3c5b738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_precios', sa.Column('precio_anterior', sa.Float(), nullable=True))
    op.create_index(op.f('ix_historial_precios_precio_anterior'), 'historial_precios', ['precio_anterior'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_precios_precio_anterior'), table_name='historial_precios')
    op.drop_column('historial_precios', 'precio_anterior')
    # ### end Alembic commands ###
