"""se añadio columna subtotal en detalle de venta

Revision ID: 7487e5ea6296
Revises: e27c3e0d9721
Create Date: 2025-10-28 13:32:59.148017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7487e5ea6296'
down_revision: Union[str, Sequence[str], None] = 'e27c3e0d9721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_venta', sa.Column('sub_total', sa.Float(), nullable=True))
    op.create_index(op.f('ix_detalles_venta_sub_total'), 'detalles_venta', ['sub_total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_venta_sub_total'), table_name='detalles_venta')
    op.drop_column('detalles_venta', 'sub_total')
    # ### end Alembic commands ###
