"""se cambiaron las tablas

Revision ID: a2f450519a68
Revises: 
Create Date: 2025-11-09 11:27:47.110820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f450519a68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_index(op.f('ix_cargos_tipo'), 'cargos', ['tipo'], unique=False)
    op.create_table('categorias',
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categorias_id_categoria'), 'categorias', ['id_categoria'], unique=False)
    op.create_index(op.f('ix_categorias_tipo'), 'categorias', ['tipo'], unique=False)
    op.create_table('clientes',
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_clientes_direccion'), 'clientes', ['direccion'], unique=False)
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('usuario_ebay', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_index(op.f('ix_proveedores_apellido'), 'proveedores', ['apellido'], unique=False)
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_index(op.f('ix_proveedores_pais'), 'proveedores', ['pais'], unique=False)
    op.create_index(op.f('ix_proveedores_tipo'), 'proveedores', ['tipo'], unique=False)
    op.create_index(op.f('ix_proveedores_usuario_ebay'), 'proveedores', ['usuario_ebay'], unique=False)
    op.create_table('emails',
    sa.Column('id_email', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_email')
    )
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=False)
    op.create_index(op.f('ix_emails_id_email'), 'emails', ['id_email'], unique=False)
    op.create_table('empleados',
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('id_cargo', sa.BigInteger(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id_cargo'], ),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleados_activo'), 'empleados', ['activo'], unique=False)
    op.create_index(op.f('ix_empleados_apellido'), 'empleados', ['apellido'], unique=False)
    op.create_index(op.f('ix_empleados_email'), 'empleados', ['email'], unique=False)
    op.create_index(op.f('ix_empleados_nombre'), 'empleados', ['nombre'], unique=False)
    op.create_index(op.f('ix_empleados_password_hash'), 'empleados', ['password_hash'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.BigInteger(), nullable=True),
    sa.Column('costo_venta', sa.INTEGER(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_productos_cantidad'), 'productos', ['cantidad'], unique=False)
    op.create_index(op.f('ix_productos_costo_venta'), 'productos', ['costo_venta'], unique=False)
    op.create_index(op.f('ix_productos_descripcion'), 'productos', ['descripcion'], unique=False)
    op.create_index(op.f('ix_productos_id_producto'), 'productos', ['id_producto'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('telefonos',
    sa.Column('id_telefono', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_telefono')
    )
    op.create_index(op.f('ix_telefonos_id_telefono'), 'telefonos', ['id_telefono'], unique=False)
    op.create_index(op.f('ix_telefonos_num'), 'telefonos', ['num'], unique=False)
    op.create_table('detalles_proveedor',
    sa.Column('id_dp', sa.BigInteger(), nullable=False),
    sa.Column('id_producto', sa.BigInteger(), nullable=True),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('id_empleado', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_dp')
    )
    op.create_index(op.f('ix_detalles_proveedor_cantidad'), 'detalles_proveedor', ['cantidad'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_detalle'), 'detalles_proveedor', ['detalle'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_id_dp'), 'detalles_proveedor', ['id_dp'], unique=False)
    op.create_index(op.f('ix_detalles_proveedor_precio_unit'), 'detalles_proveedor', ['precio_unit'], unique=False)
    op.create_table('historial_precios',
    sa.Column('id_historial', sa.BigInteger(), nullable=False),
    sa.Column('id_producto', sa.BigInteger(), nullable=True),
    sa.Column('precio_anterior', sa.Float(), nullable=True),
    sa.Column('precio_nuevo', sa.Float(), nullable=True),
    sa.Column('fecha_de_cambio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_precios_id_historial'), 'historial_precios', ['id_historial'], unique=False)
    op.create_index(op.f('ix_historial_precios_precio_anterior'), 'historial_precios', ['precio_anterior'], unique=False)
    op.create_index(op.f('ix_historial_precios_precio_nuevo'), 'historial_precios', ['precio_nuevo'], unique=False)
    op.create_table('ventas',
    sa.Column('id_venta', sa.BigInteger(), nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=True),
    sa.Column('id_empleado', sa.BigInteger(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_index(op.f('ix_ventas_id_venta'), 'ventas', ['id_venta'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id_dv', sa.BigInteger(), nullable=False),
    sa.Column('id_venta', sa.BigInteger(), nullable=True),
    sa.Column('id_producto', sa.BigInteger(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_dv')
    )
    op.create_index(op.f('ix_detalles_venta_cantidad'), 'detalles_venta', ['cantidad'], unique=False)
    op.create_index(op.f('ix_detalles_venta_detalle'), 'detalles_venta', ['detalle'], unique=False)
    op.create_index(op.f('ix_detalles_venta_id_dv'), 'detalles_venta', ['id_dv'], unique=False)
    op.create_index(op.f('ix_detalles_venta_precio_unit'), 'detalles_venta', ['precio_unit'], unique=False)
    op.create_index(op.f('ix_detalles_venta_sub_total'), 'detalles_venta', ['sub_total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_venta_sub_total'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_precio_unit'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_id_dv'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_detalle'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_cantidad'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_ventas_id_venta'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_historial_precios_precio_nuevo'), table_name='historial_precios')
    op.drop_index(op.f('ix_historial_precios_precio_anterior'), table_name='historial_precios')
    op.drop_index(op.f('ix_historial_precios_id_historial'), table_name='historial_precios')
    op.drop_table('historial_precios')
    op.drop_index(op.f('ix_detalles_proveedor_precio_unit'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_id_dp'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_detalle'), table_name='detalles_proveedor')
    op.drop_index(op.f('ix_detalles_proveedor_cantidad'), table_name='detalles_proveedor')
    op.drop_table('detalles_proveedor')
    op.drop_index(op.f('ix_telefonos_num'), table_name='telefonos')
    op.drop_index(op.f('ix_telefonos_id_telefono'), table_name='telefonos')
    op.drop_table('telefonos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id_producto'), table_name='productos')
    op.drop_index(op.f('ix_productos_descripcion'), table_name='productos')
    op.drop_index(op.f('ix_productos_costo_venta'), table_name='productos')
    op.drop_index(op.f('ix_productos_cantidad'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_empleados_password_hash'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_nombre'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_email'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_apellido'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_activo'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_emails_id_email'), table_name='emails')
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_proveedores_usuario_ebay'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_tipo'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_pais'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_apellido'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_direccion'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_tipo'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id_categoria'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_cargos_tipo'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
