"""nuevos atributos a la tabla proveedor

Revision ID: bc8fdf1cb819
Revises: 1f578c049465
Create Date: 2025-10-13 21:31:16.114792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8fdf1cb819'
down_revision: Union[str, Sequence[str], None] = '1f578c049465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('usuario_ebay', sa.String(), nullable=True))
    op.add_column('proveedores', sa.Column('pais', sa.String(), nullable=True))
    op.add_column('proveedores', sa.Column('tipo', sa.String(), nullable=True))
    op.create_index(op.f('ix_proveedores_pais'), 'proveedores', ['pais'], unique=False)
    op.create_index(op.f('ix_proveedores_tipo'), 'proveedores', ['tipo'], unique=False)
    op.create_index(op.f('ix_proveedores_usuario_ebay'), 'proveedores', ['usuario_ebay'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proveedores_usuario_ebay'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_tipo'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_pais'), table_name='proveedores')
    op.drop_column('proveedores', 'tipo')
    op.drop_column('proveedores', 'pais')
    op.drop_column('proveedores', 'usuario_ebay')
    # ### end Alembic commands ###
