"""error en telefono

Revision ID: cabe236e6646
Revises: bc8fdf1cb819
Create Date: 2025-10-14 19:17:20.995237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabe236e6646'
down_revision: Union[str, Sequence[str], None] = 'bc8fdf1cb819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefonos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefonos_id'), 'telefonos', ['id'], unique=False)
    op.create_index(op.f('ix_telefonos_num'), 'telefonos', ['num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telefonos_num'), table_name='telefonos')
    op.drop_index(op.f('ix_telefonos_id'), table_name='telefonos')
    op.drop_table('telefonos')
    # ### end Alembic commands ###
