"""Ultimas tablas de salida y historial

Revision ID: ccc0c3c5b738
Revises: cabe236e6646
Create Date: 2025-10-18 22:00:46.884453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc0c3c5b738'
down_revision: Union[str, Sequence[str], None] = 'cabe236e6646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_direccion'), 'clientes', ['direccion'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    op.create_table('historial_precios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_producto', sa.BigInteger(), nullable=True),
    sa.Column('precio_nuevo', sa.Float(), nullable=True),
    sa.Column('fecha_de_cambio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_precios_id'), 'historial_precios', ['id'], unique=False)
    op.create_index(op.f('ix_historial_precios_precio_nuevo'), 'historial_precios', ['precio_nuevo'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=True),
    sa.Column('id_empleado', sa.BigInteger(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_venta', sa.BigInteger(), nullable=True),
    sa.Column('id_producto', sa.BigInteger(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_venta_cantidad'), 'detalles_venta', ['cantidad'], unique=False)
    op.create_index(op.f('ix_detalles_venta_detalle'), 'detalles_venta', ['detalle'], unique=False)
    op.create_index(op.f('ix_detalles_venta_id'), 'detalles_venta', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_precio_unit'), 'detalles_venta', ['precio_unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_venta_precio_unit'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_detalle'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_cantidad'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_historial_precios_precio_nuevo'), table_name='historial_precios')
    op.drop_index(op.f('ix_historial_precios_id'), table_name='historial_precios')
    op.drop_table('historial_precios')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_direccion'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
