"""se añadio columna total a ventas(salida)

Revision ID: e27c3e0d9721
Revises: 3478bfda4cf8
Create Date: 2025-10-27 23:51:59.513545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27c3e0d9721'
down_revision: Union[str, Sequence[str], None] = '3478bfda4cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'total')
    # ### end Alembic commands ###
